"""add image for rooms

Revision ID: 1605ac13253d
Revises: 86faf9ad5b1f
Create Date: 2024-08-19 01:21:45.477509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1605ac13253d'
down_revision = '86faf9ad5b1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetingroom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetingroom', schema=None) as batch_op:
        batch_op.drop_column('image_id')

    # ### end Alembic commands ###
