"""Add description to MeetingRoom

Revision ID: 83de7aba1e8e
Revises: 107a927c01fd
Create Date: 2024-06-11 23:43:20.450396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83de7aba1e8e'
down_revision = '107a927c01fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetingroom', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetingroom', 'description')
    # ### end Alembic commands ###
